# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49f252b444ff11779f16a94700725aefa649d3aa97b4d459fa2a5065a39166a49e0bdf248f4a2359920a690721f8d5bc6d4998f937b9c2036d95f3fac1babaee

test:
  secret_key_base: 92680b6ca21f3ae743b3335c3408866bf543e1d4ebc261ffdf1d01af04a437f1930cd6f2ece18cf1ec37e1f29ec2afc529620fdd87d2ace83b16b3967abe841d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
